using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LoopFlow.Models
{
    [Table("SupplierInvoices")]
    public class SupplierInvoice
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string InvoiceNumber { get; set; }

        public int OrderId { get; set; }

        [ForeignKey("OrderId")]
        public virtual PurchaseOrder Order { get; set; }

        public int SupplierId { get; set; }

        [ForeignKey("SupplierId")]
        public virtual Supplier Supplier { get; set; }

        [Column(TypeName = "decimal")]
        public decimal Amount { get; set; }

        [StringLength(10)]
        public string Currency { get; set; } = "KES";

        public DateTime InvoiceDate { get; set; } = DateTime.UtcNow;

        public DateTime? DueDate { get; set; }

        [Required]
        [StringLength(50)]
        public string Status { get; set; } = "PENDING_VERIFICATION"; // PENDING_VERIFICATION, VERIFIED, REJECTED, PAID, CANCELLED

        [StringLength(50)]
        public string VerificationStatus { get; set; } = "PENDING_VERIFICATION"; // PENDING_VERIFICATION, VERIFIED, REJECTED

        public string RejectionReason { get; set; }

        [StringLength(255)]
        public string DuplicateCheckHash { get; set; }

        public string Notes { get; set; }

        public bool IsAutoGenerated { get; set; } = true;

        public bool PostedToBank { get; set; } = false;

        [StringLength(255)]
        public string DocumentUrl { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    }
}
